path: 
      src: "./"         #path of data src e.g: "C:/COR_PASIVOS/COR_AWS-DATOS"
      dest: "./export"  #dest path of exported files

site: "COR" 
#-----SITE INFO-----#
#locations:
#"COR"
#"TUC""
#"VM"
#"SMN"
#"NQN"
#"BAR"
#"TRW"
#"COM"
#"OAPA"

#-----INSTRUM INFO-----#
#instrum: "PIRA-UVA-UVB" or "AWS"
instrum: "PIRA-UVA-UVB"

file_name: "COR_AWS.dat" #name of src file e.g: "COR_AWS.dat"
